/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Calculate calculate = new Calculate();
        int sumAB = calculate.sumAB(2, 3);
        double aveAB = calculate.aveAB(sumAB);

        int sumA2B = calculate.sumA2B(1, 10);
        double aveA2B = calculate.aveA2B(sumA2B, 1, 10);

        int odd = calculate.sumOfoddA2B(1, 10);
        int even = calculate.sumOfevenA2B(1, 10);

        System.out.println("Sum of 2 and 3 is " + sumAB + ". Average is " + aveAB + ".");
        System.out.println("Sum of 1 to 10 is " + sumA2B + ". Average is " + aveA2B + ".");
        System.out.println("Sum of odd of 1 to 10 is " + odd + ". Sum of even is " + even + ".");
    }
}
